// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrs2VWv4BxLDqel_p0dM9AgzygGyaI-hc',
    appId: '1:782078404687:web:8708dff91773589838e23a',
    messagingSenderId: '782078404687',
    projectId: 'cyberclaw-go',
    authDomain: 'cyberclaw-go.firebaseapp.com',
    storageBucket: 'cyberclaw-go.firebasestorage.app',
    measurementId: 'G-3P3ZXLMD2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZVQd5uQvY4Gz8QpsAq45fjhMe2vC4FA',
    appId: '1:782078404687:android:03bd0eab1ef3200138e23a',
    messagingSenderId: '782078404687',
    projectId: 'cyberclaw-go',
    storageBucket: 'cyberclaw-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0n-TbPf6bQ06ICi_hZHkOsLoseUTOWg',
    appId: '1:782078404687:ios:16fb36dc108c79c438e23a',
    messagingSenderId: '782078404687',
    projectId: 'cyberclaw-go',
    storageBucket: 'cyberclaw-go.firebasestorage.app',
    iosBundleId: 'com.hejitech.cyberclaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0n-TbPf6bQ06ICi_hZHkOsLoseUTOWg',
    appId: '1:782078404687:ios:16fb36dc108c79c438e23a',
    messagingSenderId: '782078404687',
    projectId: 'cyberclaw-go',
    storageBucket: 'cyberclaw-go.firebasestorage.app',
    iosBundleId: 'com.hejitech.cyberclaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrs2VWv4BxLDqel_p0dM9AgzygGyaI-hc',
    appId: '1:782078404687:web:488243014c76603b38e23a',
    messagingSenderId: '782078404687',
    projectId: 'cyberclaw-go',
    authDomain: 'cyberclaw-go.firebaseapp.com',
    storageBucket: 'cyberclaw-go.firebasestorage.app',
    measurementId: 'G-LRHF8GYNLC',
  );

}